apiVersion: v1
kind: Service
metadata:
  name: cityservice
  namespace: dev
  labels:
    app: cityservice
spec:
  type: ClusterIP
  selector:
    app: cityservice
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
