---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cityservice
  namespace: dev
  labels:
    app: cityservice
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.cityserviced: semver:~2.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: cityservice
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: cityservice
    spec:
      initContainers:
      - name: init
        image: alpine:3.10.1
        command:
        - sleep
        - "1"
      containers:
      - name: cityserviced
        image: thomaspetit/city-service-thorntail:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ZIPCODE_SERVICE_URL
          value: http://cityservice-dev.192.168.99.100.nip.io
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: 1500m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 64Mi
